### ISSUE TITLE
24G torch.cuda.OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by Essence9999** [thu-coai/BPO#1]
24G玩不了

**Comment by chengjl19** [comment]
Yes, if you want to fine-tune the 7b model with full parameters, a 24G GPU memory is indeed somewhat limited. However, the core of BPO lies in the prompt optimization pairs which could reflect human preferred features. Regarding the training method, you can completely adopt techniques like lora, etc.
