### ISSUE TITLE
Does BPO model support prompt output in Chinese?

### ISSUE THREAD

**Issue by huangyongk** [thu-coai/BPO#13]
Thank you for sharing your model.
I'm interested in learning more details. Does the BPO model support input and output in Chinese language corpora? How can it be configured to produce Chinese-language results?

I've tried to switch input as Chinese or ask to provide CN output, it doesn't work right now

**Comment by chengjl19** [comment]
Currently we only support English input and output, we will consider developing models in Chinese scenarios,  and a problem lies in the lack of high-quality feedback data in Chinese.
