### ISSUE TITLE
有一些典型的场景中，部分文本内容不应该被bpo内容改变，例如 阅读理解，选择题选项等 ，这类文本如何控制不被改变

### ISSUE THREAD

**Issue by JennieGao-njust** [thu-coai/BPO#15]
我们使用了BPO的方法训练了中文的模型，想通过BPO提升在c-eval上的评测准确率， 
由于c-eval评测是选择题，我们遇到了一些问题：
1. 模型并没有按照形式把prompt进行选择题的改造，这个可能跟我们的中文数据格式较少有关；
![bpo1](https://github.com/thu-coai/BPO/assets/96759404/5eb1a2da-8eb5-45e8-b62b-6898db3455b3)
2. 模型对选项发生了更改；这个我们并不希望发生，请问有什么办法保护部分不应被修改的文本改变

**Comment by chengjl19** [comment]
Nice try! I likewise think BPO has a lot of potential for leaderboards. If you want to solve the problem you mentioned, I have two suggestions: 1. add more data, only guaranteed amount of data can have good results 2. you can add some special tokens before and after the fields you want to protect when training the model, such as [protected] [\protected], etc., which will allow the model to learn better what content should not be changed.
