### ISSUE TITLE
降低基座模型的大小，出现重复内容的现象

### ISSUE THREAD

**Issue by JennieGao-njust** [thu-coai/BPO#16]
因为当前基座是7B的模型，如果在实际使用中，BPO使用作为优化prompt的方法，7B bpo+7B 模型，如果不能表现比14B的精度，则会性价比偏低；
我们把采用了2B 以下的支持中英文的预训练模型。
遇到了的问题主要是：
1. 出现的模型推理结果，有重复内容的现象；
例如下图，response中 ，问题被复述了两次；
![bpo2](https://github.com/thu-coai/BPO/assets/96759404/ddeedd7e-9fe8-47fb-b685-a8e1d8c9dba5)

可能是因为预训练模型较小，优化后的instruction已经有了context内容，
对instruction+'\n'+context的连接中的'\n‘等连接符敏感，重复context内容，有可能把\n当成了context的起始，
另外似乎对数据中的举例数据，举例数据对good res是一个重复
请问相关实验中，是否遇到过上述问题；

**Comment by chengjl19** [comment]
You can choose to use a special token like [context] and [\context] to mark the context. This may help.

**Comment by JennieGao-njust** [comment]
> You can choose to use a special token like [context] and [\context] to mark the context. This may help.

Thank you

**Comment by benchen4395** [comment]
> > You can choose to use a special token like [context] and [\context] to mark the context. This may help.
> 
> Thank you

is this method useful?

**Comment by JennieGao-njust** [comment]
> > > You can choose to use a special token like [context] and [\context] to mark the context. This may help.
> > 
> > 
> > Thank you
> 
> is this method useful?

Sorry, my research on BPO alignment technology has stopped due to project changes. So I didn't do this experiment. However, in other experiments , I still found this problem, which is a common phenomenon of language models. According to the statement in the link https://www.zhihu.com/question/616130636, beam search during decoding or forcibly adjusting the distribution should be effective methods; hope It can help you.
