### ISSUE TITLE
如果对数据中加入role字段，也许可以在bpo这一步做到控制对话风格

### ISSUE THREAD

**Issue by JennieGao-njust** [thu-coai/BPO#18]

**Comment by chengjl19** [comment]
yep! It's a good idea, you can refer to this: https://browse.arxiv.org/pdf/2310.00152.pdf

**Comment by JennieGao-njust** [comment]
> yep! It's a good idea, you can refer to this: https://browse.arxiv.org/pdf/2310.00152.pdf

感谢！
