### ISSUE TITLE
请问代码适用于Qwen、chatglm2大模型吗？

### ISSUE THREAD

**Issue by zijinchen** [thu-coai/BPO#2]
如题，期待您的回复～

**Comment by chengjl19** [comment]
Our fine-tuning code refers to this (https://github.com/ssbuild/llm_finetuning), which supports several models. Also you can find the training code for Qwen and chatglm2 in the section “友情链接”.

**Comment by zijinchen** [comment]
感谢您的回复，还有一个小问题希望您百忙之中解答一下～


请问为什么模型的训练集、测试集输入有4个特征，而模型推理时只需要输入一个特征呢？


1、如模型的训练数据所示：https://huggingface.co/datasets/THUDM/BPO，包含optimized_prompt、prompt、bad_res、good_res四个特征
2、但是模型推理时：https://github.com/thu-coai/BPO，貌似只需要输入text，就可以输出resp






发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chengjl19 ***@***.***&gt;
发送时间: 2023年11月20日 23:33
收件人: thu-coai/BPO ***@***.***&gt;
抄送: zijinchen ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [thu-coai/BPO] 请问代码适用于Qwen、chatglm2大模型吗？ (Issue #2)





 
Our fine-tuning code refers to this (https://github.com/ssbuild/llm_finetuning), which supports several models. Also you can find the training code for Qwen and chatglm2 in the section “友情链接”.

**Comment by chengjl19** [comment]
please refer to issue#6
