### ISSUE TITLE
Where is Aligning Large Language Models "without Model Training"?

### ISSUE THREAD

**Issue by cuongnguyengit** [thu-coai/BPO#22]
Hi author,

According to my understanding, I don't need to train the model at all, I just need the llms api and datasets.
I don't see it in your project.

Can you show me where it is?

Thanks.

**Comment by chengjl19** [comment]
Actually, we emphasise no training of the generator, which can be an open-sourced or API-based LLM. Only a smaller model needs to be fine-tuned for prompt optimization to help further align the generator with human preferences.
