### ISSUE TITLE
请问BPO支持上下文吗？

### ISSUE THREAD

**Issue by van1129** [thu-coai/BPO#3]

**Comment by chengjl19** [comment]
The current model does not support multiple rounds and can only optimize single-turn, but we believe that multi-round BPO will also be effective in alignment and we leave this for future work.

**Comment by van1129** [comment]
Thank you so much. Our company is dedicated to developing voice interaction products, and we're quite intrigued by BPO . We believe it has the potential to greatly enhance the user experience of our products.

With that in mind, I would like to ask for your advice on how we can integrate it into our products more efficiently, based on your deep understanding of BPO, to optimize and improve the interaction quality. Could you provide some specific suggestions or best practices?

I look forward to your valuable insights and would like to thank you once again for your support and cooperation.

**Comment by chengjl19** [comment]
I don't know a lot about speech generation, but I believe voice interaction and text are essentially the same. So, perhaps a similar process can be adopted. Firstly, collect some data with human preferences, then use BPO to obtain an optimization model. After that, maybe consider integrating this optimization model directly into the generation pipeline (depends on your application), perform some reprocessing of the user's input, before inputting it into the actual generator. Furthermore, implementing multi-turn BPO is also fairly easy, we just need to use multi-turn human feedback data and include the conversation history during the optimization. Hope this helps you.

**Comment by van1129** [comment]
Thank you for your response. As you mentioned, indeed, we have completed the bidirectional conversion between voice and text through ASR and TTS . Therefore, it is unequivocal that what we are actually invoking with the LLM  is text. However, a characteristic of voice interaction is that users' language tends to be very brief, and much of the necessary information must be extracted from the context (in multi-turn conversations).
Therefore,I would like to konw whether we can directly utilize our existing BPO for this purpose. For example, if we introduce the context information in the format of [CLS] I am a student [SEP] I like studying [SEP], can we obtain satisfactory BPO results? Or must we retrain a model based on multi-turn dialogue data?

**Comment by chengjl19** [comment]
you can try using this single-turn model, but I think maybe retrain a model is necessary not only because of muti-round but also our model focuses on instruction-following tasks instead of chatting.

**Comment by van1129** [comment]
Got it, thanks!
