### ISSUE TITLE
请问为什么模型的训练集、测试集输入有4个特征，而模型推理时只需要输入一个特征呢？

### ISSUE THREAD

**Issue by zijinchen** [thu-coai/BPO#6]
您好

1、如模型的训练数据所示：https://huggingface.co/datasets/THUDM/BPO，包含optimized_prompt、prompt、bad_res、good_res四个特征
2、但是模型推理时：https://github.com/thu-coai/BPO，貌似只需要输入text，就可以输出resp

这里有点疑惑，感谢您的回复～

**Comment by chengjl19** [comment]
If you just want to get a prompt optimization model, you only need to use 'prompt' and 'optimized_prompt' to train the model. We keep 'good_res' and 'bad_res' to make it easier for you to reproduce the process of constructing the data, and we have carefully filtered and corrected these data. It can also support RLHF training, like DPO.

**Comment by Jialiang123** [comment]
您好，打扰了。看到这个issues，想请问一下，我如果直接用'prompt' and 'optimized_prompt构造数据集，使用llama2-7b-chat作为主干模型训练一个prompt optimization model，这个过程是不是就是个SFT训练，得到的模型实际上就是基于llama2-7b-chat做完SFT后的一个微调模型
