### ISSUE TITLE
请问BPO模型的输出可以设置为中文吗？

### ISSUE THREAD

**Issue by zijinchen** [thu-coai/BPO#8]
亲爱的作者您好：

我有注意到您文中有提到“The data in BPO are in English.”，我尝试过输入中文的prompt，模型输出的优化prompt却是英文。

请问如果我想实现输入中文prompt得到中文优化prompt的目标，基于您原始的BPO模型可以实现吗？还是说我需要基于中文的训练数据重新训练BPO模型才可以呢？

感谢您的回复～

**Comment by chengjl19** [comment]
Our training data is in English, so it is expected to get English output. If you want to build a BPO model for Chinese LLMs, more training data in Chinese are needed.
